README.md Updated
UA1252TAQC/codewars1225 pull request #229
Opened 2024-08-14 16:47 UTC by AndriyVel05

2024-08-14 19:27 UTC, smelovd requested changes

2024-08-14 19:27 UTC, smelovd commented on README.md
> +- Java 8 or later
remove section

2024-08-14 19:27 UTC, smelovd commented on README.md
> +
remove section

2024-08-14 19:27 UTC, smelovd commented on README.md
> +
remove section

2024-08-14 19:27 UTC, smelovd commented on README.md
> +    - Launch the `UIController` in your IDE.
remove line

2024-08-14 19:27 UTC, smelovd commented on README.md
> +
add image

2024-08-15 13:47 UTC, AndriyVel05 commented on README.md
> +- Java 8 or later
Java 8 or later removed.

2024-08-15 14:30 UTC, closed without merging