Added test ReadDoubleArray
UA1252TAQC/codewars1225 pull request #329
Opened 2024-08-18 18:38 UTC by Vladyslava-Nezhnova

2024-08-18 18:39 UTC, YanOleks approved these changes

2024-08-18 18:39 UTC, Oyne approved these changes

2024-08-18 20:56 UTC, smelovd requested changes
add array size check <= 0 (check string array parser) and fix method in console scanner

2024-08-19 10:09 UTC, smelovd approved these changes

2024-08-19 10:09 UTC, merged