Fixed readInt_Test
UA1252TAQC/codewars1225 pull request #443
Opened 2024-08-21 17:53 UTC by AndriyVel05

2024-08-21 18:46 UTC, smelovd requested changes

2024-08-21 18:46 UTC, smelovd commented on src/test/java/org/academy/codewars/ConsoleScannerTest.java
> +        assertEquals(outputStream.toString().trim(), expectedOutput.trim());
remove trim() method

2024-08-21 18:46 UTC, smelovd commented on src/test/java/org/academy/codewars/dataproviders/ConsoleScannerDataProvider.java
> +        String lineSeparator = System.lineSeparator();
remove variable

2024-08-22 07:47 UTC, smelovd requested changes

2024-08-22 07:47 UTC, smelovd commented on src/test/java/org/academy/codewars/ConsoleScannerTest.java
> +        assertEquals(outputStream.toString(), expectedOutput.replaceAll("\\n|\\r\\n", System.lineSeparator()));
remove replace all

2024-08-22 07:47 UTC, smelovd commented on src/test/java/org/academy/codewars/dataproviders/ConsoleScannerDataProvider.java
> +        String expectedOutput2 = "Enter a " + param + " (int): Invalid data format. An integer is expected.\nEnter a " + param + " (int): ";
use " + System.lineseparator() + ", instead \n, move it after expectedOutput1

2024-08-22 08:34 UTC, sbekberov approved these changes

2024-08-22 08:34 UTC, merged